version: "3.3"

services:
  mysql:
    image: mysql:8.0.37-debian
    container_name: "${PROJECT_NAME}_mysql"
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume:
